# Generated by Django 4.0.1 on 2022-01-18 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 21, 34, 19, 60887, tzinfo=utc)),
        ),
    ]
