# Generated by Django 4.0.1 on 2022-01-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
